### PR TITLE
Embed ghcide as a git submodule

### PR DESCRIPTION
**Pull request by pepeiborra**
Some people do not like git submodules, so this might be overkill

### CODE REVIEW

**Comment by ndmitchell** [comment]
I was assuming we'd just depend on the released version of ghcide - much like ghcide does for hie-bios.

**Comment by pepeiborra** [comment]
Wouldn't the development version of `ide` depend on the development version of `ghcide` ?

**Comment by alanz** [comment]
During development you often need to work on both

**Comment by alanz** [comment]
and the stack.yaml needs to be updated too

**Pull request merged**
